In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import math
import torch.nn.functional as F
import cv2

/home/ps/anaconda3/envs/yolo/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
import cv2

img = cv2.imread("/media/ps/data/train/LQ/LQ/bdms/bdmask/workspace/models/JT/JT-imgs/2222/odd.jpg", 0)
img = cv2.resize(img, (2144, 3584))
cv2.imwrite("/media/ps/data/train/LQ/LQ/bdms/bdmask/workspace/models/JT/JT-imgs/2222/odd-3584-2144.jpg", img)

In [ ]:

a = torch.randint(0,10, (2,3,4))
k,p,q = list(map(int, a.shape))
k,p,q = map(int, a.shape)
print(k, p, q)
# print(k, p, q)

In [2]:
def load_tensor(file):

    with open(file, "rb") as f:
        binary_data = f.read()

    magic_number, ndims, dtype = np.frombuffer(binary_data, np.uint32, count=3, offset=0)
    assert magic_number == 0xFCCFE2E2, f"{file} not a tensor file."

    dims = np.frombuffer(binary_data, np.uint32, count=ndims, offset=3 * 4)
    print(magic_number, ndims, dtype)
    if dtype == 0:
        np_dtype = np.float32
    elif dtype == 1:
        np_dtype = np.float16
    else:
        assert False, f"Unsupport dtype = {dtype}, can not convert to numpy dtype"

    return np.frombuffer(binary_data, np_dtype, offset=(ndims + 3) * 4).reshape(*dims)

In [3]:
def load_tensor222(file):

    with open(file, "rb") as f:
        binary_data = f.read()

    magic_number, ndims, dtype = np.frombuffer(binary_data, np.uint32, count=3, offset=0)
    assert magic_number == 0xFCCFE2E2, f"{file} not a tensor file."

    dims = np.frombuffer(binary_data, np.uint32, count=ndims, offset=3 * 4)
    # print(ndims, dims, dtype)

    if dtype == 0:
        np_dtype = np.float32
    elif dtype == 1:
        np_dtype = np.float16
    elif dtype == 3:
          np_dtype = np.uint8
          return np.frombuffer(binary_data, np_dtype, offset=(ndims + 3) * 4).reshape(*dims)
    else:
        assert False, f"Unsupport dtype = {dtype}, can not convert to numpy dtype"

    return np.frombuffer(binary_data, np_dtype, offset=(ndims + 3) * 4).reshape(*dims)

In [9]:
from scipy.ndimage import gaussian_filter

In [19]:
def gaussian_smooth(x, sigma=4):
    im_blur = np.zeros(x.shape, dtype=np.uint8)
    bs = x.shape[0]
    for idx in range(bs):
        im_blur[idx] = gaussian_filter(x[idx], sigma=sigma)

    return im_blur

In [11]:
def rescale(x):
    return (x - x.min()) / (x.max() - x.min())

In [22]:
file = r"/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice_lwz/run/used/512-S-0723-2-retrain-none-onlyresize-add98-retrain/tmp/tensor"
outpath = r'/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice_lwz/run/used/512-S-0723-2-retrain-none-onlyresize-add98-retrain/tmp/tensor-c++222.png'
img = load_tensor222(file)
print(img.shape)
img = img[0].transpose(1,2,0)
print(img.shape)
# img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
cv2.imwrite(outpath, img)

(1, 3, 512, 512)
(512, 512, 3)


True

In [15]:
file = r"/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice0827/tmp/splice0827/tmp/output_array_device"
outpath = r'/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice0827/tmp/splice0827/tmp/output_array_device-c++222.png'
img = load_tensor222(file)
print(img.shape)
img = img.squeeze()
print(img.shape)
cv2.imwrite(outpath, img)

(1, 512, 256)
(512, 256)


True

In [17]:
file = r"/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice0827/tmp/splice0827/tmp/output"
outpath = r'/media/ps/data1/train/LQ/task/anomalib/datasets/fsk_pad/splice0827/tmp/splice0827/tmp/output-c++222.png'
img = load_tensor222(file)
# threshold = 0.4
print(img.shape)
# img = img[0].transpose(1,2,0)

img = img.squeeze()
print(img.shape)
# img = gaussian_smooth(img, sigma=4)
# mask = rescale(img).squeeze()
# mask[mask > threshold] = 255
# mask[mask <= threshold] = 0

img = np.clip(img, 0, 1) * 255
img = cv2.threshold(img, 20, 255, cv2.THRESH_BINARY)[1]
# cv2.imwrite(outpath, img)
# img = img.reshape(3584, 2144, 3)
# img.shape
# img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
cv2.imwrite(outpath, img)

# im.shape
# cv2.imwrite(outpath, im)
# plt.imshow(mask.squeeze(),cmap="gray")

# plt.imsave(outpath, im, cmap="gray")

# print(im.shape)


(1, 1, 512, 256)
(512, 256)


True

In [22]:
tmp_py = np.load(r"/media/ps/data1/train/LQ/task/anomalib/datasets/pad/ct_splice2/run/export/inf/tmp-Image.npy",  allow_pickle=True)
different_indices = np.where(tmp_py != img)[0]
print(len(different_indices))

714224


In [11]:
import math

In [13]:
def mul(h, w):
    list = [8, 16, 32, 64, 128]
    sum = 0
    for i in list:
        sum += (math.ceil(h / i ) * math.ceil(w / i))
        
        print(h/i, w/i, math.ceil(h / i) , math.ceil(w / i))
    return sum
# mul(2048, 2048)
# mul(1952, 2592)
mul(2592, 1952)


324.0 244.0 324 244
162.0 122.0 162 122
81.0 61.0 81 61
40.5 30.5 41 31
20.25 15.25 21 16


105368

In [ ]:
2048/8 * 2048 /8 + 2048/16 * 2048 /16 + 2048/32 * 2048 /32

In [ ]:
int(3648 / 64+0.5) * int(5472/64+0.5)

In [ ]:
int(3648 / 16+0.5) * int(5472/16+0.5)

In [ ]:
int(3648 / 128+0.5) * int(5472/128+0.5)

In [ ]:
3648 / 128

In [ ]:
311904+77976+19494+4902+1247

In [5]:
seed = 123
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

a = torch.randint(1, 10, (2,3))
a

tensor([[5, 2, 4],
        [1, 2, 6]])

In [ ]:
b = torch.randint(1, 10, (2,3))
b

In [ ]:
a- b

In [ ]:
torch.sub(a, b)

In [ ]:
a+b

In [ ]:
torch.add(a, b).shape

In [ ]:
ttt = torch.randint(1, 10, (2,))
ttt = ttt[..., None]
ttt.shape

In [ ]:
def compute_locations(h, w, stride, device):
    shifts_x = torch.arange(
        0, w * stride, step=stride,
        dtype=torch.float32, device=device
    )       # [0,8,16,24,...,2040]
    shifts_y = torch.arange(
        0, h * stride, step=stride,
        dtype=torch.float32, device=device
    )       # [0,8,16,24,...,2040]
    shift_y, shift_x = torch.meshgrid(shifts_y, shifts_x)
    shift_x = shift_x.reshape(-1)
    shift_y = shift_y.reshape(-1)
    # print(shift_x)
    # print(shift_y)
    locations = torch.stack((shift_x, shift_y), dim=1) + stride // 2
    return locations

In [ ]:
h = 3648
w = 5472
strides = [8,16,32,64,128]
device = "cuda:3"
for stride in strides:
    h_step = math.ceil(h / stride)
    w_step = math.ceil(w / stride)
    locations = compute_locations(h_step, w_step, stride, device)
    print(h_step, w_step, stride, locations.shape)
    print(locations[:15])


In [ ]:
shifts_y = torch.tensor([3,4,5,6,7])
shifts_x = torch.tensor([2,3,3,4])
yx, xy = torch.meshgrid(shifts_y, shifts_x)

shift_x = xy.reshape(-1)
shift_y = yx.reshape(-1)
print(yx.shape, xy.shape)
locations = torch.stack((shift_x, shift_y), dim=1) + stride // 2
print(yx, xy, locations.shape)

In [ ]:
import torch
from glob import glob
import os.path as osp
import imagesize

In [ ]:
src = r"/media/ps/data/train/LQ/LQ/bdms/yolov7/datasets/coco128/images/train"
imps = glob(src + "/*.jpg")
dic = []
for idx, imp in enumerate(imps):
    # print(imagesize.get(imp))
    h, w  = imagesize.get(imp)
    dic.append({
        "filename":imp,
        "height":h,
        "width":w
    })
dataloader = torch.utils.data.DataLoader(dic)
print(dataloader)
for datas in dataloader:
    print(datas)

In [ ]:
torch.manual_seed(0)
a = torch.randint(1, 10, (1,1,2,4), dtype=torch.float32)
coeffs = F.interpolate(a, scale_factor=4,
                            mode='bilinear', align_corners=False)


print(a[0,0,0], "\n",coeffs[0,0,0], a.shape, coeffs.shape)

In [9]:
import cv2

src  = r'/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/odd.jpg'
img = cv2.imread(src, 1)
size = img.shape
print(img.shape)
new_h = (size[0] + 32) // 32 * 32
new_w = (size[1] + 32) // 32 * 32
print(new_w, new_h)
# mat = np.array([
#     [1, 0, (- new_w + size[1]) * 2.0],
#     [0, 1, (- new_h + size[0]) * 2.0]
# ], dtype=np.float32)

mat = np.array([
    [1, 0, 0],
    [0, 1, 0]
], dtype=np.float32)
print(mat)
nimg =  cv2.warpAffine(img, mat, (new_w, new_h), borderValue=(0,0,0))
# nimg.shape
# plt.imshow(nimg[..., ::-1])

cv2.imwrite(r'/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/222222222.jpg', nimg)

(3555, 2117, 3)
2144 3584
[[1. 0. 0.]
 [0. 1. 0.]]


True

In [ ]:
!cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/home/ps/anaconda3/envs/py-38/lib/python3.8/site-packages/trtpy/cpp-packages/build  \
OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ..