In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import math
import torch.nn.functional as F
import cv2

In [ ]:
import cv2

img = cv2.imread("/media/ps/data/train/LQ/LQ/bdms/bdmask/workspace/models/JT/JT-imgs/2222/odd.jpg", 0)
img = cv2.resize(img, (2144, 3584))
cv2.imwrite("/media/ps/data/train/LQ/LQ/bdms/bdmask/workspace/models/JT/JT-imgs/2222/odd-3584-2144.jpg", img)

In [ ]:

a = torch.randint(0,10, (2,3,4))
k,p,q = list(map(int, a.shape))
k,p,q = map(int, a.shape)
print(k, p, q)
# print(k, p, q)

In [2]:
def load_tensor(file):

    with open(file, "rb") as f:
        binary_data = f.read()

    magic_number, ndims, dtype = np.frombuffer(binary_data, np.uint32, count=3, offset=0)
    assert magic_number == 0xFCCFE2E2, f"{file} not a tensor file."

    dims = np.frombuffer(binary_data, np.uint32, count=ndims, offset=3 * 4)

    if dtype == 0:
        np_dtype = np.float32
    elif dtype == 1:
        np_dtype = np.float16
    else:
        assert False, f"Unsupport dtype = {dtype}, can not convert to numpy dtype"

    return np.frombuffer(binary_data, np_dtype, offset=(ndims + 3) * 4).reshape(*dims)

In [ ]:
file = r"/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/2222"
outpath = r'/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/2222.jpg'
img = load_tensor(file)
img = img[0].transpose(1,2,0)
# img = img.reshape(3584, 2144, 3)
img.shape
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite(outpath, img)

# im.shape
# cv2.imwrite(outpath, im)
# plt.imshow(im,cmap="gray")

# plt.imsave(outpath, im, cmap="gray")

# print(im.shape)


In [3]:
2048*2048
(3648, 5472)
(3648, 5472)

(3648, 5472)

In [4]:
def mul(h, w):
    list = [8, 16, 32, 64, 128]
    sum = 0
    for i in list:
        sum += (int(h / i+0.5) * int(w / i+0.5))
    return sum
# mul(2048, 2048)
mul(2048, 2048)

87296

In [ ]:
2048/8 * 2048 /8 + 2048/16 * 2048 /16 + 2048/32 * 2048 /32

In [ ]:
int(3648 / 64+0.5) * int(5472/64+0.5)

In [ ]:
int(3648 / 16+0.5) * int(5472/16+0.5)

In [ ]:
int(3648 / 128+0.5) * int(5472/128+0.5)

In [ ]:
3648 / 128

In [ ]:
311904+77976+19494+4902+1247

In [5]:
seed = 123
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

a = torch.randint(1, 10, (2,3))
a

tensor([[5, 2, 4],
        [1, 2, 6]])

In [ ]:
b = torch.randint(1, 10, (2,3))
b

In [ ]:
a- b

In [ ]:
torch.sub(a, b)

In [ ]:
a+b

In [ ]:
torch.add(a, b).shape

In [ ]:
ttt = torch.randint(1, 10, (2,))
ttt = ttt[..., None]
ttt.shape

In [ ]:
def compute_locations(h, w, stride, device):
    shifts_x = torch.arange(
        0, w * stride, step=stride,
        dtype=torch.float32, device=device
    )       # [0,8,16,24,...,2040]
    shifts_y = torch.arange(
        0, h * stride, step=stride,
        dtype=torch.float32, device=device
    )       # [0,8,16,24,...,2040]
    shift_y, shift_x = torch.meshgrid(shifts_y, shifts_x)
    shift_x = shift_x.reshape(-1)
    shift_y = shift_y.reshape(-1)
    # print(shift_x)
    # print(shift_y)
    locations = torch.stack((shift_x, shift_y), dim=1) + stride // 2
    return locations

In [ ]:
h = 3648
w = 5472
strides = [8,16,32,64,128]
device = "cuda:3"
for stride in strides:
    h_step = math.ceil(h / stride)
    w_step = math.ceil(w / stride)
    locations = compute_locations(h_step, w_step, stride, device)
    print(h_step, w_step, stride, locations.shape)
    print(locations[:15])


In [ ]:
shifts_y = torch.tensor([3,4,5,6,7])
shifts_x = torch.tensor([2,3,3,4])
yx, xy = torch.meshgrid(shifts_y, shifts_x)

shift_x = xy.reshape(-1)
shift_y = yx.reshape(-1)
print(yx.shape, xy.shape)
locations = torch.stack((shift_x, shift_y), dim=1) + stride // 2
print(yx, xy, locations.shape)

In [ ]:
import torch
from glob import glob
import os.path as osp
import imagesize

In [ ]:
src = r"/media/ps/data/train/LQ/LQ/bdms/yolov7/datasets/coco128/images/train"
imps = glob(src + "/*.jpg")
dic = []
for idx, imp in enumerate(imps):
    # print(imagesize.get(imp))
    h, w  = imagesize.get(imp)
    dic.append({
        "filename":imp,
        "height":h,
        "width":w
    })
dataloader = torch.utils.data.DataLoader(dic)
print(dataloader)
for datas in dataloader:
    print(datas)

In [ ]:
torch.manual_seed(0)
a = torch.randint(1, 10, (1,1,2,4), dtype=torch.float32)
coeffs = F.interpolate(a, scale_factor=4,
                            mode='bilinear', align_corners=False)


print(a[0,0,0], "\n",coeffs[0,0,0], a.shape, coeffs.shape)

In [9]:
import cv2

src  = r'/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/odd.jpg'
img = cv2.imread(src, 1)
size = img.shape
print(img.shape)
new_h = (size[0] + 32) // 32 * 32
new_w = (size[1] + 32) // 32 * 32
print(new_w, new_h)
# mat = np.array([
#     [1, 0, (- new_w + size[1]) * 2.0],
#     [0, 1, (- new_h + size[0]) * 2.0]
# ], dtype=np.float32)

mat = np.array([
    [1, 0, 0],
    [0, 1, 0]
], dtype=np.float32)
print(mat)
nimg =  cv2.warpAffine(img, mat, (new_w, new_h), borderValue=(0,0,0))
# nimg.shape
# plt.imshow(nimg[..., ::-1])

cv2.imwrite(r'/media/ps/data/train/LQ/task/bdm/bdmask/workspace/models/JT/JT-imgs/2222/222222222.jpg', nimg)

(3555, 2117, 3)
2144 3584
[[1. 0. 0.]
 [0. 1. 0.]]


True